version: "3.9"

services:
  backend:
    build: ./backend
    container_name: secure-notes-backend
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: secure-notes-frontend
    environment:
      VITE_API_URL: /api
    depends_on:
      - backend
    restart: unless-stopped

  nginx-proxy:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: notes-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
