version: "3.9"

services:
  backend:
    build: ./backend
    container_name: secure-notes-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: secure-notes-frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://13.60.60.57:8000
    depends_on:
      - backend
    restart: unless-stopped