version: "3.9"

services:
  db:
    image: postgres:15
    container_name: secure-notes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes-app-db
    command: ["postgres", "-c", "password_encryption=md5"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: secure-notes-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env.prod
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        ENV: prod
    container_name: secure-notes-frontend
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

  nginx-proxy:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: notes-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data: