version: "3.9"

services:
  backend:
    build: ./backend
    container_name: secure-notes-backend
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: secure-notes-frontend
    environment:
      VITE_API_URL: https://scriobh.io
    depends_on:
      - backend
    restart: unless-stopped

  nginx-proxy:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: notes-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
