name: Python tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: notes-app-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: notes-app-db
      DB_SSL_MODE: disable
      DB_POOL_MIN: 1
      DB_POOL_MAX: 5
      DB_TIMEOUT: 10
      PYTHONPATH: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python -m pip install --upgrade pip
      - run: pip install -r backend/requirements.txt

      - name: Confirm Postgres is accepting connections
        run: |
          for i in {1..15}; do
            PGPASSWORD=postgres psql -h localhost -U postgres -d notes-app-db -c '\q' && break
            echo "Waiting for Postgres to accept connections..."
            sleep 2
          done

      - name: Debug DB env vars
        run: |
          echo "DB_USER=$DB_USER"
          echo "DB_PASSWORD=$DB_PASSWORD"
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
          echo "DB_NAME=$DB_NAME"
          echo "DB_SSL_MODE=$DB_SSL_MODE"

      - name: Run Alembic migrations
        run: alembic -c backend/alembic.ini upgrade head

      - name: Run tests
        run: pytest -v --cov=backend --cov-report=term-missing