name: Python tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_NAME: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      PYTHONPATH: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python -m pip install --upgrade pip
      - run: pip install -r backend/requirements.txt

      - name: Confirm Postgres is accepting connections
        run: |
          for i in {1..15}; do
            PGPASSWORD=postgres psql -h postgres -U postgres -d postgres -c '\q' && break
            echo "Waiting for Postgres to accept connections..."
            sleep 2
          done

      - name: Create .env.test for compatibility
        run: |
          echo "DB_USER=postgres" > backend/.env.test
          echo "DB_PASSWORD=postgres" >> backend/.env.test
          echo "DB_HOST=postgres" >> backend/.env.test
          echo "DB_NAME=postgres" >> backend/.env.test
          echo "DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres" >> backend/.env.test

      - name: Debug DB connection string
        run: echo "DATABASE_URL=$DATABASE_URL"

      - name: Run Alembic migrations
        run: alembic -c backend/alembic.ini upgrade head

      - name: Run tests
        run: pytest -v --cov=backend --cov-report=term-missing